project_id = "xzyveouixrqkhwhllprw"

[functions.edit-vehicle-image]
verify_jwt = false

[functions.get-autos]
verify_jwt = false

[functions.agente-egana]
verify_jwt = false

[functions.manychat-webhook]
verify_jwt = false
